### ISSUE TITLE
C9v3 Look option

### ISSUE THREAD

**Issue by sr229** [pylonide/pylon#54]
While the C9v2 is the only OSS type of Cloud9, some of the people will be thrown away of the old UI. We should provide the classic C9v3 skins on C9v2 because it has a better UX, and the fact its easy to navigate to.

**Comment by exsilium** [comment]
Definitely, going forward the UI should be modernized and providing a familiar C9v3 skin would totally make sense.

**Comment by Morabaraba** [comment]
Tagging onto this issue, because I feel it is related.

I'm wondering how to add items to submenu like "Open Terminal Here":

#### Currently PylonIDE

![image](https://user-images.githubusercontent.com/11364489/48229861-f1306f80-e3b1-11e8-8f17-b58243c4d1ff.png)

#### Currently C9

![image](https://user-images.githubusercontent.com/11364489/48229845-ebd32500-e3b1-11e8-9b73-d451a2f22b21.png)

Did have a quick look at the development wiki. But I think I might be a bit to optimistic on how easy it would be to add menu items?

> familiar C9v3 skin

I'm at the moment using the `monokai` theme that looks close enough for me to the c9 `Classic Dark Gray` theme.

Maybe start a wiki list somewhere of look and feel we want to share?

**Comment by sr229** [comment]
@Morabaraba its possible but @exsilium is figuring out how the API works here (Extensions included), as the documentation has probably disappeared, and we need to reverse-engineer how the API works right now.

**Comment by exsilium** [comment]
@Morabaraba , documentation is a sad story around this project. There wasn't much to begin with and the little that there was on the c9 site has long since disappeared. Writing extensions is pretty much summed up here: https://github.com/pylonide/pylon/wiki/How-to-write-an-extension

To add contextual menu items to the tree is actually quite straight forward. Check the code for the `ext.uploadfiles' as an example reference: https://github.com/pylonide/pylon/blob/93e127a58f0b549114c557527f20dae1fb1fbacd/plugins-client/ext.uploadfiles/uploadfiles.js#L73

If you want to wiki document around the Theme then you are welcome to do so even in this Repo's wiki if that suits your needs. Let me know and I can grant the needed access. Cheers! :beers:

**Comment by sr229** [comment]
@exsilium I think GitHub has some archive.org snapshots, maybe we can recover the long lost docs from there?

**Comment by Morabaraba** [comment]
@exsillium thanks I hacked my own `apf.item` that calls `tty.elements.newTerminal.click()`.

Now I just need to tell the newTerminal my path... wip.

**Comment by exsilium** [comment]
Once complete. make sure to file a pull request. Happy to pull that feature. :smile: :+1: Cheers!

**Comment by Morabaraba** [comment]
@exsilium at the moment I'm at the following simple hack:

```js
                    mnuCtxTree.insertBefore(new apf.item({
                        id : "mnuCtxOpenTerminalHere",
                        match : "[folder]",
                        visible : "{trFiles.selected.getAttribute('type')=='folder'}",
                        caption : "Open terminal here",
                        onclick : function(e) {
                            ext.initExtension(_self);

                            var selectedNode = e.opener.selected;
                            var path = selectedNode.getAttribute("path");
                            if (tty.windows.length == 0) {
                                tty.elements.newTerminal.click();
                            }

                            var newTab = tty.windows[0].createTab();
                            newTab.send("cd ." + path + "\n");
                        }
                    }), itemCtxTreeNewFile),
```

Nicely tucked away at line 73 in `pylon/plugins-client/ext.uploadfiles/uploadfiles.js` as suggested by you.

This example forces you to work out of `$HOME/workspace` and also leave `cd ...` in the terminal.

So might make the send command rather `newTab.send(" cd '." + path + "' && clear \n");`, wip.

suggestions?

**Comment by exsilium** [comment]
I've been away - work took me elsewhere, @Morabaraba - were you able to solve this? Instead of sending the command after terminal window opening, I'd suggest you build the support directly to the terminal plugin to allow sending the workdir when creating a new term window/tab.

**Comment by exsilium** [comment]
Closing this as it has become sort of a stale issue, especially in light of #48. UI modernization is certainly a thing for the future and different plugins can be written to provide extra functionality that is currently missing but there's no specific goal to keep parity with c9v3 look.
