### ISSUE TITLE
Installation,  apf-packager verification fails

### ISSUE THREAD

**Issue by digitizer0** [pylonide/pylon#87]
npm WARN tarball tarball data for apf-packager@https://github.com/pylonide/apf-packager/tarball/master (sha512-yKV6m/iu4z8u/d0Sl39GqYBo2TPfRYo1AZVCW3X9n3Okb+4H+SfFIpPgM3ulBDdC5/NwPMSPKfSn4mRLmAsV2Q==) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open '/srv/pylon/node_modules/.staging/apf-packager-096528ac/projects/defines_3.0.xml'

**Comment by exsilium** [comment]
Hi @digitizer0 and thanks for reporting this. It's due to unforeseen impact after the `apf-packager` project got archived and merged to this repo. The master version no longer corresponds to the same checksum that is listed in the `package-lock.json` file.

For now, prior to the next release, you can remove the `package-lock.json` and re-run `npm i`. You can also remove the `apf-packager` development dependency from `package.json` while you are at it. Hope this helps! Cheers!
